# Generated by Django 5.2.5 on 2025-09-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeynessResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_text', models.TextField()),
                ('method', models.CharField(max_length=50)),
                ('results', models.JSONField()),
                ('uploaded_total', models.IntegerField()),
                ('corpus_total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
